
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/nav";
import localFont from "next/font/local";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Gir.Digital",
  description: "Generated by create next app",
};

const myFont = localFont({
  src: "../public/fonts/LXGWWenKaiGBScreen.ttf",
  display: "swap",
  preload: true
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`bg-black font-custom`}>
      <body
        className={`${inter.className} ${myFont.className} antialiased max-w-3xl mb-40 flex flex-col md:flex-row mx-8 mt-8 lg:mx-auto`}
      >
        <main className="flex-auto min-w-0 mt-6 flex flex-col px-2 md:px-0">
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
